blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
	validates :title , presence: true,
						length: { minimum: 5 }
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
	@articles = Article.all
end
def new
    @article = Article.new
end

def edit
  @article = Article.find(params[:id])
end

def update
  @article = Article.find(params[:id])
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def show
    @article = Article.find(params[:id])
end

def create
    @article = Article.new(article_params)
    if @article.save
        redirect_to @article
    else
        render 'new'
    end
end

private
    def article_params
        params.require(:article).permit(:title, :text)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Updating</title>
</head>
<body>
	
<h1>Edit article</h1>
 
<%= form_for (@article) do |f| %>
 
  
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :Text %><br>
    <%= f.text_area :Text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
</body>
</html>

blog/app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>All articles</title>
</head>
<body>
	<ul>
		<%  @articles.each do |article| %>
			<li><%=article.title%> __ <%=article.Text%></li>
		<%= link_to 'Show' , article_path(article) %>
		<%= link_to 'Back', articles_path %>
		<%= link_to 'Destroy', article, method: :delete %>
		<%= link_to 'Patch', article, method: :patch %>
		<% end %>
	</ul>

</body>
</html>

blog/app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %>
			<br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :Text %>
		<br>
		<%= f.text_area :Text %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

blog/app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
		<%= @article.title %>

</p>
<p>
	<strong>
		Text:
		<%= @article.Text %>
	</strong>
	<%= link_to  'Back', articles_path %>
	
</p>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New Article', new_article_path %>